id: I2163BF94
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T04:46:34+00:00'
last_modified: '2022-06-08T11:04:23.031026+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC287
  title: 'ཡིག་གཟུགས་མིག་གི་བདུད་རྩི། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    6A84:
      image_group_id: I2PD17820
      title: ''
      total_pages: 220
      order: 1
      base_file: 6A84.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
