id: P009443
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1AC287
  title: 'ཡིག་གཟུགས་མིག་གི་བདུད་རྩི། '
  author: ''
  volumes:
    86722d53e359472e9130b70bdfdc2450:
      image_group_id: I2PD17820
      title: ''
      volume_number: 1
      total_pages: 220
      base_file: v001.txt
